[tool.poetry]
name = "info6205-python"
version = "0.1.0"
description = ""
authors = ["Sraw <lzyl888@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
